### ISSUE TITLE
Access Denied when deploying Ingress

### ISSUE THREAD

**Issue by MarcusRosen-Rio** [aws-quickstart/quickstart-kubernetes-resource-provider#20]
Hi,

I'm trying to deploy an Ingress resource using the AWSQS::Kubernetes::Resource. The cloudformation role is setup is configured as member of system:masters and I'm able to deploy the template manually using kubectl command line.

This is the template:

```
InternalArtifactoryIngress:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: !Ref ArtifactoryK8Namespace
      Manifest: !Sub
        |
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        metadata:
          name: artifactory-ha-external-ingress
          namespace: artifactory-ha
          annotations:
            # Ref: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internal
            alb.ingress.kubernetes.io/target-type: instance
            alb.ingress.kubernetes.io/tags: Name=Artifactory-Internal-Ingress
            alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
            alb.ingress.kubernetes.io/healthcheck-path: /router/api/v1/system/health
            alb.ingress.kubernetes.io/ssl-redirect: '443'
            alb.ingress.kubernetes.io/ip-address-type: ipv4
            alb.ingress.kubernetes.io/certificate-arn: ${ArtifactoryACMCertificateArn}
        spec:
          rules:
            - http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      serviceName: ${TargetServiceName}
                      servicePort: 8080
```

`Code: Exception Message: apiVersion: v1items: []kind: Listmetadata:  resourceVersion: ""  selfLink: ""Error from server (Forbidden): ingresses.networking.k8s.io is forbidden: User "" cannot list resource "ingresses" in API group "networking.k8s.io" in the namespace "artifactory-ha"`

I'm not sure, but it looks like the IAM context from the role is not resolved in K8 ??
