### ISSUE TITLE
Internal Handler Error

### ISSUE THREAD

**Issue by cedkoerber** [aws-quickstart/quickstart-kubernetes-resource-provider#28]
When trying to use the sample code for creating the configmap in the default namespace an error would be thrown by cloudformation.
<img width="1271" alt="config-map-error-message" src="https://user-images.githubusercontent.com/100222074/155171523-d221cc00-9cdf-4ac5-8bb5-99ebab3029b3.PNG">

This was resolved by tagging the private subnets associated with the EKS Cluster with the following tag and value. kubernetes.io/role/internal-elb   1

Hope this helps anyone else running into this issue

**Comment by git4rk** [comment]
I am trying "AWSQS::Kubernetes::Resource" `apply` and running into same error, even after changing all private subnets to `kubernetes.io/role/internal-elb 1`:
`"Resource handler returned message: "" (RequestToken: abf0b623-c82d-6a55-3e1d-4c8113235db3, HandlerErrorCode: InternalFailure)"`

Template snippet:
```
Resources:
  OpenLibertyCRD:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: default
      Url: https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/main/deploy/releases/0.8.0/kubectl/openliberty-app-crd.yaml
```

I created EKS using EKS Quick Start. Not sure if that matters.
Any suggestion on what else could be wrong?
