### ISSUE TITLE
No logs sent to CloudWatch Logs

### ISSUE THREAD

**Issue by scott-brady** [aws-quickstart/quickstart-kubernetes-resource-provider#32]
Hello. I am using the QuickStart Kubernetes Resource Provider via the CloudFormation Public Registry, and cannot get it to write logs to CloudWatch. This is making it difficult to troubleshoot other issues such as errors, timeouts, etc.

I can reproduce this issue via the following steps.

1. Deploy a CloudFormation stack using the following template:

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  AwsQuickStartKubernetesTypeResourceAutoUpdate:
    AllowedValues: [ "false", "true" ]
    Default: "true"
    Description: >-
      Whether to automatically update the AWSQS::Kubernetes::Resource extension in this account and region when a new
      minor version is published by the extension publisher. Major versions released by the publisher must be manually
      updated.
    Type: String

  AwsQuickStartKubernetesTypeResourceLogGroupRetentionInDays:
    Default: "7"
    Description: >-
      Number of days to retain CloudWatch logs for the AWSQS::Kubernetes::Resource extension.
    Type: Number

  AwsQuickStartKubernetesTypeResourceMajorVersion:
    Default: "1"
    Description: >-
      The major version of the AWSQS::Kubernetes::Resource extension you want to activate, if multiple major versions
      are available. The default is the latest major version. CloudFormation uses the latest available minor version of
      the major version selected.
    Type: String

  ClusterName:
    Type: String
    Description: Cluster name for the EKS cluster

  EksClusterEndpointPublicAccess:
    Type: String
    Description: Whether to expose the Kubernetes control plane APIs publicly.
    AllowedValues: [ "false", "true" ]
    Default: "true"

  EksClusterLogGroupRetentionInDays:
    Type: Number
    Description: Number of days to retain EKS cluster control plane logs in CloudWatch log group.
    Default: "7"

  EksClusterVersion:
    Type: String
    Description: Kubernetes version of the EKS cluster.
    AllowedValues: [ "1.21", "1.22", "1.23" ]
    Default: "1.23"

  InstanceType:
    Type: String
    Description: Instance type to be used for node groups

  NodeGroupInstancesMaxLimit:
    Type: Number
    Description: Maximum limit for node group instances

  PrivateSubnetId1:
    Type: String
    Description: Private subnet Ids

  PrivateSubnetId2:
    Type: String
    Description: Private subnet Ids

  PrivateSubnetId3:
    Type: String
    Description: Private subnet Ids

  VpcCidr:
    Type: String
    Description: CIDR of the target VPC.

  VpcId:
    Type: String
    Description: VPC to create the EC2 resources in.

Resources:

  # Based on: https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider/blob/main/execution-role.template.yaml
  AwsQuickStartKubernetesTypeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"  # required for EKS clusters with Public Endpoint disabled
                - "resources.cloudformation.amazonaws.com"
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"  # required for deploying helm charts into non-EKS kubernetes clusters
                  - "kms:Decrypt"
                  - "eks:DescribeCluster"
                  - "s3:GetObject"
                  - "sts:AssumeRole"
                  - "sts:GetCallerIdentity"
                  - "iam:PassRole"  # required for EKS clusters with Public Endpoint disabled
                  - "ec2:CreateNetworkInterface"  # required for EKS clusters with Public Endpoint disabled
                  - "ec2:DescribeNetworkInterfaces"  # required for EKS clusters with Public Endpoint disabled
                  - "ec2:DeleteNetworkInterface"  # required for EKS clusters with Public Endpoint disabled
                  - "ec2:DescribeVpcs"  # required for EKS clusters with Public Endpoint disabled
                  - "ec2:DescribeSubnets"  # required for EKS clusters with Public Endpoint disabled
                  - "ec2:DescribeRouteTables"  # required for EKS clusters with Public Endpoint disabled
                  - "ec2:DescribeSecurityGroups"  # required for EKS clusters with Public Endpoint disabled
                  - "logs:CreateLogGroup"  # required for EKS clusters with Public Endpoint disabled
                  - "logs:CreateLogStream"  # required for EKS clusters with Public Endpoint disabled
                  - "logs:PutLogEvents"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:UpdateFunctionConfiguration"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:DeleteFunction"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:GetFunction"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:InvokeFunction"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:CreateFunction"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:UpdateFunctionCode"  # required for EKS clusters with Public Endpoint disabled
                  - "logs:CreateLogGroup"  # required if this role is also used for Resource type logging
                  - "logs:CreateLogStream"  # required if this role is also used for Resource type logging
                  - "logs:DescribeLogGroups"  # required if this role is also used for Resource type logging
                  - "logs:DescribeLogStreams"  # required if this role is also used for Resource type logging
                  - "logs:PutLogEvents"  # required if this role is also used for Resource type logging
                  - "cloudwatch:ListMetrics"  # required if this role is also used for Resource type logging
                  - "cloudwatch:PutMetricData"  # required if this role is also used for Resource type logging
                  - "ssm:PutParameter"  # ssm parameters are used by the ::Get resource to track requests
                  - "ssm:GetParameter"  # ssm parameters are used by the ::Get resource to track requests
                  - "ssm:DeleteParameter"  # ssm parameters are used by the ::Get resource to track requests
                Resource: "*"

  AwsQuickStartKubernetesTypeResourceLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: "/aws/cloudformation/type/resource/AWSQS-Kubernetes-Resource"
      RetentionInDays: !Ref AwsQuickStartKubernetesTypeResourceLogGroupRetentionInDays

  # AWSQS::Kubernetes::Resource: https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider
  AwsQuickStartKubernetesTypeResource:
    Type: AWS::CloudFormation::TypeActivation
    Properties:
      AutoUpdate: !Ref AwsQuickStartKubernetesTypeResourceAutoUpdate
      ExecutionRoleArn: !GetAtt AwsQuickStartKubernetesTypeExecutionRole.Arn
      LoggingConfig:
        LogGroupName: !Ref AwsQuickStartKubernetesTypeResourceLogGroup
        LogRoleArn: !GetAtt AwsQuickStartKubernetesTypeExecutionRole.Arn
      MajorVersion: !Ref AwsQuickStartKubernetesTypeResourceMajorVersion
      PublisherId: 408988dff9e863704bcc72e7e13f8d645cee8311
      Type: RESOURCE
      TypeName: AWSQS::Kubernetes::Resource

  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Communication between the control plane and worker node groups
      SecurityGroupIngress:
        - CidrIp: !Ref VpcCidr
          Description: Allow Control Plane HTTPS from VPC
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ControlPlaneSecurityGroup"
      VpcId: !Ref VpcId

  InlinePolicyForServiceRole:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: cloudwatch:PutMetricData
            Effect: Allow
            Resource: "*"
          - Action:
              - ec2:DescribeAccountAttributes
              - ec2:DescribeAddresses
              - ec2:DescribeInternetGateways
            Effect: Allow
            Resource: "*"

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: eks.amazonaws.com
      Description: Service role attached to cluster
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
        - !Ref InlinePolicyForServiceRole

  EksClusterLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/eks/${ClusterName}/cluster"
      RetentionInDays: !Ref EksClusterLogGroupRetentionInDays

  EksCluster:
    Type: AWS::EKS::Cluster
    DependsOn: EksClusterLogGroup
    Properties:
      ResourcesVpcConfig:
        EndpointPrivateAccess: true
        EndpointPublicAccess: !Ref EksClusterEndpointPublicAccess
        SecurityGroupIds:
          - !GetAtt ControlPlaneSecurityGroup.GroupId
        SubnetIds:
          - !Ref PrivateSubnetId1
          - !Ref PrivateSubnetId2
          - !Ref PrivateSubnetId3
      RoleArn: !GetAtt ServiceRole.Arn
      KubernetesNetworkConfig:
        IpFamily: ipv4
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
            - Type: authenticator
            - Type: controllerManager
            - Type: scheduler
      Name: !Ref ClusterName
      Version: !Ref EksClusterVersion

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              Iops: 3000
              Throughput: 125
              VolumeSize: 80
              VolumeType: gp3
        MetadataOptions:
          HttpPutResponseHopLimit: 2
          HttpTokens: optional
        SecurityGroupIds:
          - !GetAtt EksCluster.ClusterSecurityGroupId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "${AWS::StackName}EksClusterNode"
              - Key: alpha.eksctl.io/nodegroup-name
                Value: !Sub "${ClusterName}NodeGroup"
              - Key: alpha.eksctl.io/nodegroup-type
                Value: Managed
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub "${AWS::StackName}EksClusterNode"
              - Key: alpha.eksctl.io/nodegroup-name
                Value: !Sub "${ClusterName}NodeGroup"
              - Key: alpha.eksctl.io/nodegroup-type
                Value: Managed
          - ResourceType: network-interface
            Tags:
              - Key: Name
                Value: !Sub "${AWS::StackName}EksClusterNode"
              - Key: alpha.eksctl.io/nodegroup-name
                Value: !Sub "${ClusterName}NodeGroup"
              - Key: alpha.eksctl.io/nodegroup-type
                Value: Managed
      LaunchTemplateName: !Sub "${AWS::StackName}EksClusterLaunchTemplate"

  AutoScalingPolicyForInstanceRole:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeLaunchConfigurations
              - autoscaling:DescribeTags
              - autoscaling:SetDesiredCapacity
              - autoscaling:TerminateInstanceInAutoScalingGroup
              - ec2:DescribeLaunchTemplateVersions
            Effect: Allow
            Resource: "*"
      ManagedPolicyName: !Sub "${AWS::StackName}AutoScalingPolicyForInstanceRole"

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: !Sub "ec2.${AWS::URLSuffix}"
      Description: Role to be used by node group instances
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Ref AutoScalingPolicyForInstanceRole

  EksNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref ClusterName
      NodeRole: !GetAtt InstanceRole.Arn
      Subnets:
        - !Ref PrivateSubnetId1
        - !Ref PrivateSubnetId2
        - !Ref PrivateSubnetId3
      AmiType: AL2_x86_64
      InstanceTypes:
        - !Ref InstanceType
      LaunchTemplate:
        Id: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      NodegroupName: !Sub "${ClusterName}NodeGroup"
      ScalingConfig:
        DesiredSize: 2
        MaxSize: !Ref NodeGroupInstancesMaxLimit
        MinSize: 2

Outputs:

  AwsQuickStartKubernetesTypeExecutionRoleArn:
    Description: ARN of the AWSQS::Kubernetes::Get and AWSQS::Kubernetes::Resource resource type execution role.
    Value: !GetAtt AwsQuickStartKubernetesTypeExecutionRole.Arn

  AwsQuickStartKubernetesTypeResourceArn:
    Description: ARN of the AWSQS::Kubernetes::Resource resource type.
    Value: !Ref AwsQuickStartKubernetesTypeResource

  ClusterInstanceRole:
    Description: Role attached to ec2 instances in the cluster.
    Value: !GetAtt InstanceRole.Arn

  ClusterServiceRole:
    Description: Cluster service role.
    Value: !GetAtt ServiceRole.Arn
```

2. Grant RBAC permissions to the `AwsQuickStartKubernetesTypeExecutionRoleArn` output by the stack

```powershell
$region = "ap-southeast-2"
$clusterName = "MYEKS001"
$awsQuickStartKubernetesTypeExecutionRoleArn = "<arn from AwsQuickStartKubernetesTypeExecutionRoleArn stack output above>"

eksctl create iamidentitymapping `
    --cluster $clusterName `
    --region=$region `
    --arn $awsQuickStartKubernetesTypeExecutionRoleArn `
    --group 'system:masters' `
    --username 'admin:{{SessionName}}'
```

3. Attempt to deploy a resource using `AWSQS::Kubernetes::Resource` with the following CloudFormation template:

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  ClusterName:
    Type: String
    Description: Cluster name for the EKS cluster

Resources:

  ExampleCm:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: default
      Manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: example-cm
        data:
          example_key: example_value
```

Whether the stack completes successfully or not, I would expect to see some logs being generated in the CloudWatch Logs group named `/aws/cloudformation/type/resource/AWSQS-Kubernetes-Resource`. However there are no log streams or messages generated at all.

Could you please assist to let me know what is missing to get the logs to appear? Thanks.
