### ISSUE TITLE
Namespace creation

### ISSUE THREAD

**Issue by andromeda306** [aws-quickstart/quickstart-kubernetes-resource-provider#41]
Seems like a simple question, but how can I create a custom namespace?
The below manifest results in the following CF error `Resource handler returned message: "Namespace is required` 
```
  MyNamespace:
    Type: AWSQS::Kubernetes::Resource
    Properties:
        ClusterName: !Ref ClusterName
        Manifest: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: my-namespace
```
