### ISSUE TITLE
please consider a ResourceRoleArn property for use with AssumeRole

### ISSUE THREAD

**Issue by mdaniel** [aws-quickstart/quickstart-kubernetes-resource-provider#42]
Today, if one activates `AWSQS::Kubernetes::Resource`, it has a fixed IAM Role that it operates as. This makes it very challenging to use the custom type against multiple `AWS::EKS::Cluster` instances, since with today's IAM auth model in EKS, the resource creator is the only one which is able to initially write any resources to it

For example, given:
```yaml
Resources:
  MyAuth:
    Type: AWSQS::Kubernetes::Resource
    # ^^^ this has `ExecutionRoleArn: "arn:aws:iam::111122223333:role/Alpha"` just for our example
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: kube-system
      Manifest:
        Fn::Sub: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: aws-auth
          data:
            mapRoles: '[...]'
```
then:
```console
$ aws sts get-caller-identity
{"Arn":"arn:aws:iam::111122223333:role/Alpha"}
$ aws create-stack --stack-name s1 --template-url https://bucket.example.com/eks.yaml
# ... time passes ...
$ aws sts get-caller-identity
{"Arn":"arn:aws:iam::111122223333:role/Beta"}
$ aws create-stack --stack-name s2 --template-url https://bucket.example.com/eks.yaml
# kaboom because EKS is not owned by Alpha and thus does not trust ::Resource
```
If `::Resource` were extended to allow `ResourceRoleArn:`, and the necessary IAM `AssumeRolePolicyDocument:` were in place to trust the `ExecutionRoleArn` of the `::Resource`, then the `::Resource` could optionally `eval $(aws sts assume-role --role-arn ${ResourceRoleArn})` before trying to auth into EKS, allowing the CF type to be used in a lot more scenarios

In a hypothetical new world, it would be annoying to have to pass in the owning Role, but _possible_
```yaml
Parameters:
  MyRoleArn: { Type: String }
Resources:
  MyAuth:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref EksClusterName
      ResourceRoleArn: !Ref MyRoleArn
      Namespace: kube-system
      Manifest:
        Fn::Sub: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: aws-auth
```

---

I am open to doing this work, if it would be merged
