### ISSUE TITLE
AWSQS::Kubernetes::Resource: Update of resource triggers [Errno 2] No such file or directory: '/tmp/manifest.yaml' 

### ISSUE THREAD

**Issue by chauhansachinkr** [aws-quickstart/quickstart-kubernetes-resource-provider#9]
**Note: Cluster is setup using eks-quickstart https://github.com/aws-quickstart/quickstart-amazon-eks**
    
A reproducible test case or series of steps
1. Create a namespace using Url property to an existing cluster 

```yaml 
CloudWatchNamespace:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref ClusterName
      Url: 'https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/cloudwatch-namespace.yaml'
  ```

2. Update the same resource, but instead of URL , use Manifest property. This change will trigger the cloudformation rollback.

```yaml
  CloudWatchNamespace:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref ClusterName
      #Url: 'https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/cloudwatch-namespace.yaml'
      Manifest:
      - |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: amazon-cloudwatch
          labels:
            name: amazon-cloudwatch
```

3. Cloudformation Error message  "
<img width="950" alt="image" src="https://user-images.githubusercontent.com/7309994/103441849-85788300-4c59-11eb-965d-e7b165344cc6.png">

**Note: We have also experienced that updating the manifest file also triggers the same error**
